spring.application.name=backend

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://rahulrawat84588_db_user:tjVyEazEkU4vDwrn@cluster0.x1yxlov.mongodb.net/resume_builder

JAVA_TOOL_OPTIONS = -Djdk.tls.client.protocols=TLSv1.2

# JWT
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahulrawat84588@gmail.com
spring.mail.password=rroqfqzmfoajwbql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay
razorpay.key.id=rzp_test_TATbD1u6sX7XzI
razorpay.key.secret=B33zMJuSqd31m7k5jJGphZrX

# Cloudinary
cloudinary.cloud.name=dxt1ls10c
cloudinary.api.key=154658669971475
cloudinary.api.secret=JY4P5MbCRsPZ63oOkzkZ7_tj_hM

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB