spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/resume_builder
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000


# Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahulrawat84588@gmail.com
spring.mail.password=rroqfqzmfoajwbql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay
razorpay.key.id=rzp_test_TATbD1u6sX7XzI
razorpay.key.secret=B33zMJuSqd31m7k5jJGphZrX